bboard/bboard/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

bboard/main/urls.py
from django.urls import path

from .views import (
    BBLogoutView, 
    ProfileEditView,
    BbLoginView,
    other_page,
    profile,
    index,
    PasswordEditView,
    RegisterView,
    RegisterDoneView,
    user_activate
    )

app_name = 'main'
urlpatterns = [
    path('accounts/activate/<str:sign>/', user_activate, name='activate'),
    path('accounts/register/done/', RegisterDoneView.as_view(), name='register_done'),
    path('accounts/register/', RegisterView.as_view(), name='register'),
    path('accounts/logout/', BBLogoutView.as_view(), name='logout'),
    path('accounts/password/edit/', PasswordEditView.as_view(), name='password_edit'),
    path('accounts/profile/edit/', ProfileEditView.as_view(), name='profile-edit'),
    path('accounts/profile/', profile, name='profile'),
    path('accounts/login/', BbLoginView.as_view(), name='login'),
    path('<str:page>/', other_page, name='other'),
    path('', index, name='index'),
]

bboard/main/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class AdvUser(AbstractUser):
    is_activated = models.BooleanField(default=True, db_index=True, verbose_name='Прошёл активацию?')
    send_message = models.BooleanField(default=True, verbose_name='Слать оповещения о новых комментариях?')

    class Meta(AbstractUser.Meta):
        pass

bboard/main/forms.py
from django import forms
from django.contrib.auth import password_validation
from django.core.exceptions import ValidationError

from .signals import post_register
from .models import AdvUser

class ProfileEditForm(forms.ModelForm):
    email = forms.EmailField(required=True, label='Адрес электронной почты')

    class Meta:
        model = AdvUser
        fields = ('username', 'email', 'first_name', 'last_name', 'send_message')

class RegisterForm(forms.ModelForm):
    email = forms.EmailField(required=True, label='Адрес электронной почты')
    password1 = forms.CharField(label='Пароль', 
                                widget=forms.PasswordInput, 
                                help_text=password_validation.password_validators_help_text_html())
    password2 = forms.CharField(label='Пароль (повторно)', 
                                widget=forms.PasswordInput, 
                                help_text='Введите тот же самый пароль ещё раз для проверки')

    def clean_password1(self):
        password1 = self.cleaned_data['password1']
        if password1:
            password_validation.validate_password(password1)
        return password1
    
    def clean(self):
        super().clean()
        password1 = self.cleaned_data['password1']
        password2 = self.cleaned_data['password2']
        if password1 and password2 and password1 != password2:
            errors = {'password2': ValidationError('Введенные пароли не совпадают', code='password_mismatch')}
            raise ValidationError(errors)
    
    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        user.is_active = False
        user.is_activated = False
        if commit:
            user.save()
        post_register.send(RegisterForm, instance=user)
        return user

    class Meta:
        model = AdvUser
        fields = ('username', 'email', 'password1', 'password2', 'first_name', 'last_name', 'send_message')
    

bboard/main/views.py
from django.db.models.base import Model as Model
from django.shortcuts import render
from django.http import HttpResponse, Http404
from django.template import TemplateDoesNotExist
from django.template.loader import get_template
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView
from django.contrib.auth.decorators import login_required
from django.views.generic.edit import UpdateView, CreateView
from django.views.generic.base import TemplateView
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404
from django.core.signing import BadSignature

from .models import AdvUser
from .forms import ProfileEditForm, RegisterForm
from .utilities import signer

# Create your views here.
def index(request):
    return render(request, 'main/index.html')


def other_page(request, page):
    try:
        template = get_template('main/' + page + '.html')
    except TemplateDoesNotExist:
        raise Http404
    return HttpResponse(template.render(request=request))

class BbLoginView(LoginView):
    template_name = 'main/login.html'

class BBLogoutView(LogoutView):
    pass

@login_required
def profile(request):
    return render(request, 'main/profile.html')

class ProfileEditView(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    model = AdvUser
    template_name = 'main/profile_edit.html'
    form_class = ProfileEditForm
    success_url = reverse_lazy('main:profile')
    success_message = 'Данные пользователя изменены'

    def setup(self, request, *args, **kwargs):
        self.user_id = request.user.pk
        return super().setup(request, *args, **kwargs)
    
    def get_object(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, pk=self.user_id)
    
class PasswordEditView(SuccessMessageMixin, LoginRequiredMixin, PasswordChangeView):
    template_name = 'main/password_edit.html'
    success_url = reverse_lazy('main:profile')
    success_message = 'Пароль пользователя изменен'
    
class RegisterView(CreateView):
    model = AdvUser
    template_name = 'main/register.html'
    form_class = RegisterForm
    success_url = reverse_lazy('main:register_done')

class RegisterDoneView(TemplateView):
    template_name = 'main/register_done.html'

def user_activate(request, sign):
    try: 
        username = signer.unsign(sign)
    except BadSignature:
        return render(request, 'main/activation_failed.html')
    user = get_object_or_404(AdvUser, username=username)
    if user.is_activated:
        template = 'main/activation_done_earlier.html'
    else:
        template = 'main/activation_done.html'
        user.is_active = True
        user.is_activated = True
        user.save()
    return render(request, template)

bboard/main/templates/layout/basic.html
{% load django_bootstrap5 %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}Главная{% endblock %} - Доска объявлений</title>
    {% bootstrap_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'main/style.css' %}">
    {% bootstrap_javascript %}
</head>
<body class="container-fluid">
    <header class="mb-4">
        <h1 class="display-1 text-center">Объявления</h1>
    </header>
    <nav class="row navbar navbar-expand-md bg-light">
        <div class="col container">
            <a class="navbar-brand" href="{% url 'main:index' %}">Главная</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
                <div class="navbar-nav">
                    {% if user.is_authenticated %}
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Профиль</a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="{% url 'main:profile' %}">Мои объявления</a>
                            <a class="dropdown-item" href="{% url 'main:profile-edit' %}">Изменить личные данные</a>
                            <a class="dropdown-item" href="{% url 'main:password_edit' %}">Изменить пароль</a>
                            <hr class="dropdown-divider">
                            <form class="px-3" method='post' action='{% url 'main:logout' %}'>
                                {% csrf_token %}
                                {% bootstrap_button 'Выйти' button_class='btn-danger' %}
                            </form>
                            <hr class="dropdown-divider">
                            <a class="dropdown-item" href="#">Удалить</a>
                        </div>
                        {% else %}
                        <a class="nav-link" href="{% url 'main:register' %}">Регистрация</a>
                        <a class="nav-link" href="{% url 'main:login' %}">Вход</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </nav>
    <div class="row">
        <nav class="col-md-auto nav flex-column bg-light">
            <span class="nav-link root">Недвижимость</span>
            <a class="nav-link" href="#">Жилье</a>
            <a class="nav-link" href="#">Склады</a>
            <a class="nav-link" href="#">Гаражи</a>
            <span class="nav-link root">Транспорт</span>
            <a class="nav-link" href="#">Легковой</a>
            <a class="nav-link" href="#">Грузовой</a>
            <a class="nav-link root" href="{% url 'main:other' page='about' %}">О сайте</a>
        </nav>
        <main class="col py-2">
            {% bootstrap_messages %}
            {% block content %}
            {% endblock %}
        </main>
    </div>
    <footer class="mt-3">
        <p class="text-end fst-italic">&copy; читатели.</p>
    </footer>
</body>
</html>

bboard/main/templates/main/about.html
{% extends "layout/basic.html" %}

{% block title %}О сайте{% endblock %}

{% block content %}
<h2>О сайте</h2>
<p>Сайт для публикации объявлений о продаже, разбитых на рубрики.</p>
<p>Все права принадлежат читателям книги &laquo;Django 4&raquo;.</p>
{% endblock %}

bboard/main/templates/main/activation_done.html
{% extends "layout/basic.html" %}

{% block title %}Активация выполнена{% endblock %}

{% block content %}
<h2>Активация</h2>
<p>Пользователь с таким именем успешно активирован.</p>
<p><a href="{% url 'main:login' %}">Войти на сайт</a></p>
{% endblock %}

bboard/main/templates/main/activation_done_earlier.html
{% extends "layout/basic.html" %}

{% block title %}Пользователь уже активирован{% endblock %}

{% block content %}
<h2>Активация</h2>
<p>Пользователь с таким именем был активирован ранее.</p>
<p><a href="{% url 'main:login' %}">Войти на сайт</a></p>
{% endblock %}

bboard/main/templates/main/activation_failed.html
{% extends "layout/basic.html" %}

{% block title %}Ошибка при активации{% endblock %}

{% block content %}
<h2>Активация</h2>
<p>Активация пользователя с таким именем прошла неудачно.</p>
<p><a href="{% url 'main:register' %}">Зарегистрироваться повторно</a></p>
{% endblock %}

bboard/main/templates/main/index.html
{% extends "layout/basic.html" %}

{% block content %}
<h2>Последние 10 объявлений</h2>
{% endblock %}

bboard/main/templates/main/login.html
{% extends "layout/basic.html" %}

{% load django_bootstrap5 %}

{% block title %}Вход{% endblock %}

{% block content %}
<h2>Вход</h2>
{% if user.is_authenticated %}
<p>Вы уже выполнили вход.</p>
{% else %}
<form method="post">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    <input type="hidden" name="next" value="{{ next }}">
    {% bootstrap_button 'Войти' %}
</form>
{% endif %}
{% endblock %}

bboard/main/templates/main/password_edit.html
{% extends "layout/basic.html" %}

{% load django_bootstrap5 %}

{% block title %}Смена пароля{% endblock %}

{% block content %}
<h2>Смена пароля пользователя {{ user.username }}</h2>
<form method="post">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    {% bootstrap_button 'Сменить пароль'%}
</form>
{% endblock %}

bboard/main/templates/main/profile.html
{% extends "layout/basic.html" %}

{% block title %}Профиль пользователя{% endblock %}

{% block content %}
<h2>Профиль пользователя {{ user.username }}</h2>
{% if user.first_name and user.last_name %}
<p>Здравствуйте, {{ user.first_name }} {{ user.last_name }}!</p>
{% else %}
<p>Здравствуйте!</p>
{% endif %}
<h3>Ваши объявления</h3>
{% endblock %}

bboard/main/templates/main/profile_edit.html
{% extends "layout/basic.html" %}

{% load django_bootstrap5 %}

{% block title %}Правка личных данных{% endblock %}

{% block content %}
<h2>Правка личных данных пользователя {{ user.username }}</h2>
<form method="post">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    {% bootstrap_button 'Сохранить' %}
</form>
{% endblock %}

bboard/main/templates/main/register.html
{% extends "layout/basic.html" %}

{% load django_bootstrap5 %}

{% block title %}Регистрация{% endblock %}

{% block content %}
<h2>Регистрация нового пользователя</h2>
<form method="post">
    {% csrf_token %}
    {% bootstrap_form form layout="horizontal" %}
    {% bootstrap_button 'Зарегистрироваться' %}
</form>
{% endblock %}

bboard/main/templates/main/register_done.html
{% extends "layout/basic.html" %}

{% block title %}Регистрация завершена{% endblock %}

{% block content %}
<h2>Регистрация</h2>
<p>Регистрация пользователя завершена.</p>
<p>На адрес электронной почты, указанный пользователем, выслано письмо для активации.</p>
{% endblock %}